### ISSUE TITLE
'TypeError: Cannot read property '0' of undefined' on npm install

### ISSUE THREAD

**Issue by stevelacerda7** [rofrischmann/inline-style-prefixer#145]
I'm attempting to npm install inline-style-prefixer and receiving the following error:

```
2840 verbose stack TypeError: Cannot read property '0' of undefined
2840 verbose stack     at rmStuff (/usr/local/lib/node_modules/npm/lib/unbuild.js:61:24)
2840 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
2840 verbose stack     at ret (eval at makeNodePromisifiedEval (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
2840 verbose stack     at lifecycle.then.then (/usr/local/lib/node_modules/npm/lib/install/action/unbuild.js:12:12)
2840 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
2840 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
2840 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
2840 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
2840 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
2840 verbose stack     at Promise._fulfill (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
2840 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/nodeback.js:42:21
2841 verbose cwd /Users/slacerda/Desktop/projects/wizeye-server.wufsharp/WUFSharp/bin/Debug/client

```

Any ideas?

**Comment by stevelacerda7** [comment]
I'm going to close this issue out. I upgraded npm and it's resolved.
