### ISSUE TITLE
Build failing with Material-UI

### ISSUE THREAD

**Issue by lnmunhoz** [rofrischmann/inline-style-prefixer#92]
There is a related issue on https://github.com/callemall/material-ui/issues/4740.

This is happening when we import his file: https://github.com/callemall/material-ui/blob/adff686b16b0969112c69fcae469a7e1872e4875/src/styles/MuiThemeProvider.js

Stacktrace:
```bash
ERROR in ./~/inline-style-prefixer/lib/Prefixer.js
Module build failed: ReferenceError: Unknown plugin "transform-class-properties" specified in "/Users/lnmunhoz/workspaces/toptal/toptal-front/node_modules/inline-style-prefixer/package.json" at 0, attempted to resolve relative to "/Users/lnmunhoz/workspaces/toptal/toptal-front/node_modules/inline-style-prefixer"
    at /Users/lnmunhoz/workspaces/toptal/toptal-front/node_modules/babel-core/lib/transformation/file/options/option-manager.js:204:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/lnmunhoz/workspaces/toptal/toptal-front/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:20)
    at OptionManager.mergeOptions (/Users/lnmunhoz/workspaces/toptal/toptal-front/node_modules/babel-core/lib/transformation/file/options/option-manager.js:300:36)
    at OptionManager.addConfig (/Users/lnmunhoz/workspaces/toptal/toptal-front/node_modules/babel-core/lib/transformation/file/options/option-manager.js:232:10)
    at OptionManager.findConfigs (/Users/lnmunhoz/workspaces/toptal/toptal-front/node_modules/babel-core/lib/transformation/file/options/option-manager.js:442:30)
    at OptionManager.init (/Users/lnmunhoz/workspaces/toptal/toptal-front/node_modules/babel-core/lib/transformation/file/options/option-manager.js:484:12)
    at File.initOptions (/Users/lnmunhoz/workspaces/toptal/toptal-front/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/Users/lnmunhoz/workspaces/toptal/toptal-front/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/Users/lnmunhoz/workspaces/toptal/toptal-front/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
 @ ./~/material-ui/utils/autoprefixer.js 53:27-59
```

package.json
```json
{
  "name": "project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "webpack-dev-server",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "material-ui": "^0.15.0-beta.1",
    "react": "^15.0.1",
    "react-dom": "^15.0.1",
    "react-router": "^2.3.0"
  },
  "devDependencies": {
    "babel-core": "^6.7.4",
    "babel-loader": "^6.2.4",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "webpack": "^1.13.1",
    "webpack-dev-server": "^1.14.1"
  }
}
```

.babelrc
```js
{
  "presets": [
    "es2015",
    "react"
  ]
}
```

Any help? @oliviertassinari @cf-ssharma

**Comment by rofrischmann** [comment]
Hmm, it seems like something changed in terms of how Babel reads the babelrc or compiles node_modules. You might fix that for now by including `babel-plugin-transform-class-properties` to your devDepenendecies. I will fix this with the next release.

**Comment by lnmunhoz** [comment]
Thank you @rofrischmann!

The same thing happen with the following plugins:
- babel-plugin-add-module-exports
- babel-preset-stage-0

So basically the workaround is adding all of them in my `devDependencies`.

```bash
npm install babel-plugin-transform-class-properties babel-plugin-add-module-exports babel-preset-stage-0 --save-dev
```

**Comment by kohlmannj** [comment]
Dear @rofrischmann, humbly, I would greatly appreciate it if you could provide a release that resolves this issue. I'm working on a few internal packages and build tools which continue to stumble because of this (for example, see https://github.com/Khan/aphrodite/issues/120).

An update would really help out me and my immediate, small team of developers. Thanks for your consideration.

**Comment by oliviertassinari** [comment]
I'm wondering if it wouldn't be better to move the babel configuration into a `.babelrc` file that can be removed from the npm package.

@lnmunhoz why have you closed the issue?

**Comment by rofrischmann** [comment]
@oliviertassinari Yeah I guess that could help too. But I am not sure how Babel uses the configs at all. 
@kohlmannj Yet I'll try to push a fix before leaving for vacation. Took me some days to fix my mac, but I am back again :P

**Comment by kohlmannj** [comment]
@rofrischmann Great, really appreciate it!
